exclude = [
    "test",
]

respect-gitignore = true
line-length = 120

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
select = ["C4", "E4", "E7", "E9", "F", "UP009"]
ignore = [
# Imports:
"E402",
# Other:
"E701", "E741", "E731",
"F401", "F403", "C901"
]

[format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

quote-style = "single"
