# More syntax details at: https://docs.travis-ci.com/user/customizing-the-build
# Workaround present for https://github.com/sunqm/pyscf/issues/71

sudo: required
language: python

git:
  depth: 3

matrix:
  include:
    - dist: trusty

virtualenv:
    system_site_packages: true
    
before_install:
    - sudo apt-get -qq install gcc 
    - sudo apt-get -qq install gfortran
    - sudo apt-get -qq install libblas-dev
    - sudo apt-get -qq install liblapack-dev
    - sudo apt-get -qq install libatlas-dev
    - sudo apt-get -qq install libatlas-base-dev
    - sudo apt-get -qq install python-h5py
    - sudo apt-get -qq install python-nose
    - sudo apt-get -qq install python-numpy
    - sudo apt-get -qq install python-scipy
    - sudo apt-get -qq install cmake
    - sudo apt-get -qq install doxygen

script:
     cd pyscf/lib &&
     mkdir build &&
     cd build &&
     cmake .. &&
     make &&
     cd ../../.. &&
     export PYTHONPATH=$PWD &&
     find ./ -type f | grep test_ | xargs -I{} python {}
